version: "3.8"

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: flight_risk_postgres
    restart: always
    environment:
      POSTGRES_USER: alfredo
      POSTGRES_PASSWORD: alfredo_pass
      POSTGRES_DB: flight_risk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
